# Generated by Django 4.1.1 on 2022-09-25 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_invoice_amount_alter_invoice_invoice_number"),
    ]

    operations = [
        migrations.DeleteModel(
            name="InvoiceDetail",
        ),
    ]
