# Generated by Django 4.1.1 on 2022-09-24 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="title",
            field=models.TextField(
                default="",
                help_text="Name to identify the partner account",
                unique=True,
            ),
            preserve_default=False,
        ),
    ]
