# Generated by Django 4.1.1 on 2022-09-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0005_partnerupload"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnerupload",
            name="file_name",
            field=models.TextField(default="My File", help_text="Name of File"),
            preserve_default=False,
        ),
    ]
