# Generated by Django 4.1.1 on 2022-09-25 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0006_partnerupload_file_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnerupload",
            name="import_summary",
            field=models.TextField(default="", help_text="Summary of import"),
            preserve_default=False,
        ),
    ]
